# Generated by Django 4.0.2 on 2022-03-09 00:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_picture_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='Picture'),
        ),
    ]
